### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by wnpllrzodiac** [aofall/padavan-toolchain-mipsel#1]
cd /opt/usr/local/padavan-toolchain-master/bin
./mipsel-linux-uclibc-gcc

report 
`./mipsel-linux-uclibc-gcc: line 1: syntax error: unexpected "("`

**Comment by aofall** [comment]
It's a toolchain for Cross compiling.
You might setting the PATH such as

```
export TOOLCHAIN_DIR=/opt/usr/local/padavan-toolchain-master
PATH=$PATH:$TOOLCHAIN_DIR/bin
export PATH
```

**Comment by wnpllrzodiac** [comment]
I got it. I misunderstand that this version is run on my router. I realize I made a mistake. It SHOULD run on ubuntu to build app run on my router.
